title = "Amore : Asteroids" # The window title (string)
width = 800               # The window width (number)
height = 600              # The window height (number)
vsync = true              # Enable vertical sync (boolean)
centered = true           # Center the window in the display
msaa = 16                 # The number of samples to use with multi-sampled antialiasing (number)
