identity = ""             # The name of the save directory (string)
title = "Amore Example"   # The window title (string)
icon = ""                 # Filepath to an image to use as the window's icon (string)
width = 1280              # The window width (number)
height = 720              # The window height (number)
borderless = false        # Remove all border visuals from the window (boolean)
resizable = true          # Let the window be user-resizable (boolean)
minwidth = 1              # Minimum window width if the window is resizable (number)
minheight = 1             # Minimum window height if the window is resizable (number)
fullscreen = false        # Enable fullscreen (boolean)
fullscreentype = "normal" # Standard fullscreen or desktop fullscreen mode (string)
vsync = true              # Enable vertical sync (boolean)
msaa = 16                 # The number of samples to use with multi-sampled antialiasing (number)
display = 1               # Index of the monitor to show the window in (number)
highdpi = false           # Enable high-dpi mode for the window on a Retina display (boolean)
srgb = false              # Enable sRGB gamma correction when drawing to the screen (boolean)
centered = true           # Center the window in the display
x = -1                    # The x-coordinate of the window's position in the specified display (number)
y = -1                    # The y-coordinate of the window's position in the specified display (number)
